name: vine
description: Vine is a robust, typed validation library for Dart/Flutter, designed to simplify and secure data management in applications
version: 1.1.0
repository: https://github.com/LeadcodeDev/vine

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - validator
  - data

environment:
  sdk: ^3.5.3

dependencies:
  string_validator: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
